name: Atlas Push Migrations
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  push:
    services:
      postgres15:
        image: postgres:15
        env:
          POSTGRES_DB: test
          POSTGRES_PASSWORD: pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ariga/setup-atlas@v0
        with:
          cloud-token: ${{ secrets.ATLAS_CLOUD_TOKEN }}
      - uses: ariga/atlas-action/migrate/push@v1
        with:
          dir: 'file://db/migrations'
          dir-name: 'melody-test'
          dev-url: postgres://postgres:pass@localhost:5432/test?sslmode=disable
